### ISSUE TITLE
Problem with serial port server

### ISSUE THREAD

**Issue by julot44** [panaaj/nmeasimulator#1]
Hello,

When I set server on serial, my host doesn't receive data.
I put same settings than "NMEA Simultor for chrome".

Chrome application
![image](https://user-images.githubusercontent.com/61834938/75986831-13c39180-5eef-11ea-91cc-aa81b65437f7.png)

New application
![image](https://user-images.githubusercontent.com/61834938/75986875-23db7100-5eef-11ea-84ff-ddc9f4979f77.png)

What can I check?

Regards

**Comment by julot44** [comment]
Yes, it's correct I'm with windows version.

> You are not seeing NMEA output on the configured serial port, and placing the same settings in Chrome App outputs the NMEA data correctly on the configured serial port.

Yes, this my problem.

**Comment by panaaj** [comment]
I have identified the problem and a fix will be in the next release.

**Comment by panaaj** [comment]
@julot44  v0.2.0 is available. Please confirm this release addresses your issue.
