### ISSUE TITLE
Getting an uncaught error when not connected to the internet

### ISSUE THREAD

**Issue by probonopd** [panaaj/nmeasimulator#10]
Does this application require an internet connection?

![image](https://user-images.githubusercontent.com/2480569/90005832-17c2bf00-dc98-11ea-8c61-98076a3515c2.png)

**Comment by panaaj** [comment]
This is probably due to the version check, which requires internet access to check if a new version is available...
This is the only function that requires internet access.
I'll add a connectivity test prior to the version check.

**Comment by panaaj** [comment]
resolved in [v1.0.2](https://github.com/panaaj/nmeasimulator/releases/tag/v1.0.2https://github.com/panaaj/nmeasimulator/releases/tag/v1.0.2)

**Comment by probonopd** [comment]
Thank you very much. It is working for me now.
