### ISSUE TITLE
No output in TCP server

### ISSUE THREAD

**Issue by ronangaillard** [panaaj/nmeasimulator#11]
I spy the content sent via the TCP server using netcat, I am able to connect but there is no data.

I am using version 1.0.1 on OSX 10.15.4

**Comment by panaaj** [comment]
How is the connection being ended? Is the client connection being closed or terminated via `ctrl-c`?

**Comment by ronangaillard** [comment]
Ctrl+c

**Comment by ronangaillard** [comment]
Where is it ? :)

**Comment by panaaj** [comment]
It is undergoing final testing and will be released soon.

**Comment by panaaj** [comment]
resolved in [v1.0.2](https://github.com/panaaj/nmeasimulator/releases/tag/v1.0.2https://github.com/panaaj/nmeasimulator/releases/tag/v1.0.2)
