### ISSUE TITLE
Unable to select serial ports under Ubuntu 20.04

### ISSUE THREAD

**Issue by knapie** [panaaj/nmeasimulator#12]
I am unable to select serial ports under the server settings.

There are various tty devices available on my machine.

![Screenshot from 2020-09-04 14-57-49](https://user-images.githubusercontent.com/17121114/92241837-2bd89580-eebf-11ea-92be-884b8a3f62e6.png)

Thanks

**Comment by panaaj** [comment]
Fix has been included in release v1.0.3 which will be available very soon.

**Comment by panaaj** [comment]
[v1.0.3](https://github.com/panaaj/nmeasimulator/releases/tag/v1.0.3) released

**Comment by knapie** [comment]
Confirmed working in v1.0.3 , thank you.
