### ISSUE TITLE
Local routeable address

### ISSUE THREAD

**Issue by Flocksofseagull** [panaaj/nmeasimulator#14]
I'm trying to use this in the same way as your chrome NMEA simulator but without success. I was successfully connecting to the chrome version with R using a socket connection to whichever port it opened on 127.0.0.1, but I can't see any routeable address the current program is using. I only see a 0.0.0.0 address when starting it as web socket or TCP (server).

**Comment by panaaj** [comment]
You will need to set the IP address in the config to be the IP address of your network interface (I have also had success using `localhost`) .
