### ISSUE TITLE
Blank screen when starting the application

### ISSUE THREAD

**Issue by radupantiru** [panaaj/nmeasimulator#15]
Running on Lubuntu and connecting via VNC. When starting the app after the loading logo the window is black and could not find any errors in lmdisplay log or Xorg.0.log.

**Comment by panaaj** [comment]
Unfortunately this is not an environment I have to be able to test with.
The application does work via VNC connecting to raspian (Rasperry Pi).
Sorry but I am able to only support general use cases and offer the application for use as is.

**Comment by Jalkku** [comment]
Same thing happens with Ubuntu 18.04. The upper panel is visible, the screen with the gauges and whatnot are blank.

**Comment by panaaj** [comment]
Can you please provide a little more detail about your scenario.
Am I correct in assuming that you have installed the app on a machine running Ubuntu and are connecting to that machine via VNC to launch the app?
Did you use the .deb package or the AppImage?

**Comment by Jalkku** [comment]
Sorry about the lack of details, I do not use VNC. I've installed the .deb package and I'm running it directly from Ubuntu desktop.

**Comment by panaaj** [comment]
App is developed using Ubuntu 20.04 (inital development was done using Ubuntu 19.xx) so the app does run directly on these distros using the .deb package.
Have you tried the AppImage?
What you describe appears to be the app content not rendering which I have only seen before when trying to use a .deb package on Raspberry Pi (which is a known issue, AppImage must be used).

Can you please try the AppImage to see if you get a different result.

**Comment by Jalkku** [comment]
Thanks for the suggestion. Unfortunately using the Appimage produces the same results.

**Comment by panaaj** [comment]
No there are no log files.
I assume that your device is amd/intel powered.... I suspect the serialport driver (which is compiled for specific platforms) may be the issue. Have seen something similar when trying to run the amd appImage on an arm powered device.
