### ISSUE TITLE
Output stream frequency limitations

### ISSUE THREAD

**Issue by Zuzon** [panaaj/nmeasimulator#17]
Hi, is that possible to set data send less than each 200ms?
In my case i'm testing a performance.
as example Ublox can send 24 updates per second (~42ms interval)

**Comment by panaaj** [comment]
It is theoretically possible but will require some changes to the code to decouple the "transmitted" sentence frequency from the display update frquency.
As it currently stands providing data send rates in the realm you have requested will impact impact user experience.

I will investigate this as part of a future release.
What kind of send rates where you looking to have added 100ms, 50ms?

**Comment by Zuzon** [comment]
50ms could be enough i think

**Comment by panaaj** [comment]
v1.1.0 published includes this function
