### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by smokebarbq** [panaaj/nmeasimulator#18]
Does this application log? If so where? I'd like to archive the data for testing purposes

**Comment by panaaj** [comment]
It does not currently log.
I will put this on the backlog to add as a feature. 
Would it be also useful to playback the log file data?

**Comment by smokebarbq** [comment]
Yes it would be very useful with the log file and historical playback

**Comment by panaaj** [comment]
v1.1.0 published and includes this function
