### ISSUE TITLE
LiquidGalaxy/ViewSync Google Earth

### ISSUE THREAD

**Issue by loitepr** [panaaj/nmeasimulator#19]
How about adding ViewSync UDP to Google Earth. It would be awesome to fly around in Google Earth in 3D with this simulator. Could be set up with multiple monitors to create a truly amazing simulator - and combined with your choice of electronic sea chart.

**Comment by panaaj** [comment]
While not really a core function of this application the idea of additional output stream types does have merit e.g. Signal K.
I will look into ViewSync UDP format... if you have links to resources that would be appreciated.

**Comment by panaaj** [comment]
The next release will have support for sending ViewSync UDP messages. Stay tuned!

**Comment by loitepr** [comment]
Awesome. When can we expect it?

**Comment by panaaj** [comment]
I am in the process of finalising v1.1.0 now... hopefully on the weekend or early next week...

**Comment by panaaj** [comment]
So just to provide a little more about how NMEASimulator will suport ViewSync..
First you need to configure ViewSync in `Settings` .

![image](https://user-images.githubusercontent.com/38519157/100405135-e806be00-30b2-11eb-9114-702ab4760264.png)

When the simulator is running  ViewSync UDP packets will be sent to the configured host. The camera height and tilt can be altered whilst the simulator is running.
Yaw, roll and other values are set to 0 as we are simulating a boat after all.

All my testing was done with Google Earth desktop client with the following lines added to the SETTINGS section of the `drivers.ini` file.
```
    ViewSync/send = false
    ViewSync/receive = true
    ViewSync/port = 7001
    ViewSync/yawOffset = 0
    ViewSync/pitchOffset = 0.0
    ViewSync/rollOffset = 0.0
    ViewSync/horizFov = 36.5
```

It's basic but there you have it.

**Comment by panaaj** [comment]
v1.1.0 published
