### ISSUE TITLE
No gpx loading?

### ISSUE THREAD

**Issue by VladimirKalachikhin** [panaaj/nmeasimulator#2]
Version: 0.3.0
I want to follow by my gpx track.
I click "Follow GPX track", select track - and nothing happens. "Start Simulation" playing the default track.

**Comment by panaaj** [comment]
Can you please confirm the following:
1. What platform are you using (Windows, Mac, Linux)? If using Linux what application file are you using (.deb, .rpm. AppImage)?

2. Once a GPX file is selected a list of Tracks within the file is displayed, like the following?
Note: only tracks within the GPX file are supported.
![image](https://user-images.githubusercontent.com/38519157/77496800-b9897100-6e9b-11ea-8383-a46255a16939.png)

3. When you click on the desired Track the data is loaded and the Map centered at the starting location (you may have to zoom in to see the track) like below? If not what is displayed?
![image](https://user-images.githubusercontent.com/38519157/77496940-0a00ce80-6e9c-11ea-9f70-c226448df53d.png)

4. Clicking Start should see the vessel start to move along the track. Does the vessel follow the track?

**Comment by VladimirKalachikhin** [comment]
NMEASimulator_0.3.0_amd64.deb
No tracks displayed after selected the gpx file.

Yes! I found!
The gpx file less than about 1MB displayed fine (814kB), but above (1.1MB) - break on step 2.

**Comment by panaaj** [comment]
Is it possible for you to provide me with a copy of the file that failed so i can find out why it is causing an issue?

**Comment by VladimirKalachikhin** [comment]
https://drive.google.com/open?id=19YKcUD-FPgKEAm82I1jEkfbGsyglspI1

**Comment by panaaj** [comment]
Thanks... Looking at the file it contains two tracks:
- Trk 1 contains only 1 track point
- Trk 2 contains 2 track points

Is this correct or is there something missing from the file (it's only 1.1kb in size)

**Comment by VladimirKalachikhin** [comment]
Oh, sorry - this my mistake.
https://drive.google.com/open?id=1YgMBD0on6wTvexaZMafO6MkhAcrGZUuc

**Comment by panaaj** [comment]
Thanks.. the file size issue has been resolved. It will be in the next release.

**Comment by panaaj** [comment]
Resolved in v0.4.0
