### ISSUE TITLE
gpx tracking issue

### ISSUE THREAD

**Issue by mahmood-8** [panaaj/nmeasimulator#20]
when i import gpx file (for example 450 km) and start it to simulating it jump to end immediately and didn't follow the pre set speed.
Please tell me how to modify gpx file for this or please fix the issue
regards

**Comment by panaaj** [comment]
I cannot reproduce the issue with the GPX files I have so could you please provide a copy of the file you are having issues with.

**Comment by panaaj** [comment]
Closed due inactivity
