### ISSUE TITLE
Format of the NMEA log file for playback

### ISSUE THREAD

**Issue by rgroothuis** [panaaj/nmeasimulator#22]
It's unclear for me what the format of the NMEA log file should be for playback. 

If I put the following lines in a text file: 

!AIVDM,1,1,,A,402E3Miv0r<BCPDAjjMdjuW000S:,0*26
!AIVDM,1,1,,A,33aGFdPP00PCmFJMbrQ6Mwv`R2mQ,0*1A
!AIVDM,1,1,,B,13aN3i0P1I0CL1fMcTFDcwv`08;p,0*1B
!AIVDM,1,1,,B,139r5tP0000BPK2MacCWmi@b00Ra,0*58
!AIVDM,1,1,,B,13aDobgP00PBrsfMaj6@0?v`20SP,0*65
!AIVDM,1,1,,B,13aDpOhP1lPC0pBMfSkswgv`PD:A,0*40
!AIVDM,1,1,,A,139EKv0P010BPLFMaWWpw?vb08;w,0*68
$SDDPT,4.1,*7C
$VWMTW,7.60,C*13
!AIVDM,1,1,,B,13aK`E@P000CaKHMd4Lv4?v`P0Sn,0*4E
$GPRMC,121824.81,A,5149.480,N,00407.224,E,0.1,344.0,200316,001.0,W,D*20
$MXRMB,,,,,000F,,,,,,,,*12
$GPZDA,121824,20,03,2016,0,0*40
!AIVDM,1,1,,A,402E3Miv0r<BCPDAjjMdjuW000S:,0*26
!AIVDM,1,1,,A,33aGFdPP00PCmFJMbrQ6Mwv`R2mQ,0*1A
!AIVDM,1,1,,B,13aN3i0P1I0CL1fMcTFDcwv`08;p,0*1B

Then I get an error message that the log input file doesn't have the correct format. 
But what is the format?

**Comment by panaaj** [comment]
The supported log files for playback are ones created by the app.
The reason being that to support pausing and stepping there needs to be markers within the file to support this.
So you cannot just replay a log of NMEA sentence data.
