### ISSUE TITLE
Sending GPS Trace date and time  as per trace content

### ISSUE THREAD

**Issue by GLEPGRU** [panaaj/nmeasimulator#23]
Hie;
The GPS trace contains date and position. Would it be possible for the GPS function to send in NMEA and Signal K both the position and the date Time contained in the trace?
Thank you for help.
All my best. Nice simulator!

**Comment by panaaj** [comment]
Can you please be more specific as to your issue.
NMEA sentences e.g. RMC contain the date time if part of the sentence make up. 
e.g. $GPRMC,064358.558,A,3459.98,S,13830.01,E,4.9,13.6,__260121__,,,*0B1

Also the ZDA sentence being sent..`$GPZDA,064358.558,26,01,2021,10,30*54`

With regard to Signal K only delta messages are sent.

**Comment by GLEPGRU** [comment]
Hello;
The trace (.Gpx) file contains a list of date and positions: 
for example:
    <trkseg>
 <trkpt lat="46.4713" lon="-1.831527">
        <time>2020-11-8T12:2:0Z</time>
      </trkpt>
 <trkpt lat="46.352364" lon="-3.744569">
        <time>2020-11-8T17:17:0Z</time>
      </trkpt>
 <trkpt lat="46.358441" lon="-4.957709">
        <time>2020-11-8T20:48:0Z</time>
      </trkpt>
 <trkpt lat="46.435898" lon="-5.862571">
        <time>2020-11-8T23:30:0Z</time>
      </trkpt>

If I replay the trace using the simulator the position will be sent through Nmea and signal K but the date andtime will be the current date and time.

I woud like the date to be the one contained in the trace ie in theexemple above 2020 11 08 23:30 instead of 2020 01 26 18:23.

This in order to be able to "replay " the trace in the same conditions it was recorded.
If an option could be proposed it would be very nice!

All my best

**Comment by GLEPGRU** [comment]
@panaaj
I have also an other request for you:
I am trying to codethe generation of !AIDVM messages in order to send to Opencpn or QTvlm the position and name of virtual boats.
I Would like to code the generation of the  !AIVDM messages considering that I Know the boat name, position and time, sog and cog.
I can not find the information how to code that .
Considering you have done it in this simulator, can you help me by providing me with the algorithms or an code example (what ever the langage is)?
This would be very kind ! I am quite stuckked.:-(


Thank you for your help
All my best 
You can e mail me at Gilles.lepinard(at)laposte.net

**Comment by panaaj** [comment]
> Hello;
> The trace (.Gpx) file contains a list of date and positions:
> for example:
> 
> 
> 2020-11-8T12:2:0Z
> 
> 
> 2020-11-8T17:17:0Z
> 
> 
> 2020-11-8T20:48:0Z
> 
> 
> 2020-11-8T23:30:0Z
> If I replay the trace using the simulator the position will be sent through Nmea and signal K but the date andtime will be the current date and time.
> 
> I woud like the date to be the one contained in the trace ie in theexemple above 2020 11 08 23:30 instead of 2020 01 26 18:23.
> 
> This in order to be able to "replay " the trace in the same conditions it was recorded.
> If an option could be proposed it would be very nice!
> 
> All my best

I will look to include this in the next release.

**Comment by panaaj** [comment]
> @panaaj
> I have also an other request for you:
> I am trying to codethe generation of !AIDVM messages in order to send to Opencpn or QTvlm the position and name of virtual boats.
> I Would like to code the generation of the !AIVDM messages considering that I Know the boat name, position and time, sog and cog.
> I can not find the information how to code that .
> Considering you have done it in this simulator, can you help me by providing me with the algorithms or an code example (what ever the langage is)?
> This would be very kind ! I am quite stuckked.:-(
> 
> Thank you for your help
> All my best
> You can e mail me at Gilles.lepinard(at)laposte.net

Here is a link to a resource explaining the sentence structure. [AIVDM/VDO decoder](https://gpsd.gitlab.io/gpsd/AIVDM.html)

There are a number of different libraries out there in different languages e.g. [javascript](https://gpsd.gitlab.io/gpsd/AIVDM.html) so hopefully this points you in the right direction.

**Comment by panaaj** [comment]
closed by [v1.1.1](https://github.com/panaaj/nmeasimulator/releases/tag/v1.1.1)

**Comment by GLEPGRU** [comment]
Hie I have downloaded v1.1.1 for windows (.exe)  . I see no change with previous version (also named V1.1.1) . Am I right? something seems to be wrong. 
All my best

**Comment by panaaj** [comment]
If the GPX file contains `trkpt <time>` (as shown below) then this value is used in the playback...

```
<trkpt lat="50.716739343479276" lon="6.445662165060639">
        <ele>165.47999999999999</ele>
        <time>2012-12-03T09:10:33Z</time>
</trkpt>
```

**Comment by GLEPGRU** [comment]
Hie .
You are right my mistake
My trace was formatted like this  <time>2020-11-8T20:48:0Z</time>
If coorected with  <time>2020-11-08T20:48:00Z</time> it is ok
Thank you very much!
All my best
