### ISSUE TITLE
NMEA Output for AWS wrong

### ISSUE THREAD

**Issue by fabianfisahn** [panaaj/nmeasimulator#26]
Hello,

The output data for AWS in format "NMEA" seems to be not correct. I think the data shows the km/h value but says m/s.
Example:
$WIMWV,253.5,R,74.6,M,A*14

My settings:
Server: Web Socket
Output Stream Format: NMEA

OS: MacOS

(Signal K output works well)

**Comment by panaaj** [comment]
Fix is in the next release.

**Comment by panaaj** [comment]
closed by v1.2.0
