### ISSUE TITLE
AIVDM (Other vessel) output available?

### ISSUE THREAD

**Issue by velosol** [panaaj/nmeasimulator#27]
In the Chrome App description there's a mention of !AIVDM output but I wasn't able to find it in the Windows version (1.2.0).  I haven't tried the Chrome App so I'm not sure if it was actually available there or if you're intending the 2 to have feature parity.

Can NMEASimulator generate !AIVDM sentences?  If so, how?

I didn't see AIVDM or 'other vessel' in Help but didn't dig into code.

Thank you!

**Comment by panaaj** [comment]
Currently only the VDO message is output as this is makes more sense as it relates directly to the vessel being simulated.
I will look to add VDM message that will contain the same data as the VDO message in the next release.

**Comment by velosol** [comment]
Thank you for looking into it!  Just as a use case in the event it helps: my plan was to take the AIVDM into an AIS parser to be able to create tracks on another chart display without relying on previously captured data.

**Comment by panaaj** [comment]
closed by v1.2.1
