### ISSUE TITLE
TWA not respect COG

### ISSUE THREAD

**Issue by mirekther** [panaaj/nmeasimulator#28]
Hi, thank you for very good utility! I have one notice. 
It looks like TWA is send the same as Wind Direction in case True Wind Direction is less than 180 degrees. .
$WIMWV,75.7,T,13.2,N,A*20
$WIMWD,75.7,T,75.7,M,13.2,N,6.8,M*64
$WIMWV,42.0,R,16.3,N,A*21
There is no influence of COG of the boat (COG should be subtracted somehow I believe)
So the correct TWA is displayed if Boat is heading to the North only. 
From my point of view will be nice to have possibility to switch TWA ($WIMWV,75.7,T) sentence off, because Navigation software should be able to calculate it itself. 

Thank you very much for help.
Mirek

**Comment by panaaj** [comment]
Will remove TWA ($WIMWV,xx.x,T) sentence from output in the next release.

**Comment by panaaj** [comment]
closed by v1.2.1
