### ISSUE TITLE
Simulator Starting Values

### ISSUE THREAD

**Issue by WhyNotPal** [panaaj/nmeasimulator#29]
Hey, thanks for this great tool!!
Just a question - in the settings, there's this possibility to set some starting position - but the simulator does not seem to use them. 
In my case, whatever the values I set there, or where I "leave" my ship before closing, the ship always starts its course at Adelaide. 
Did I miss something? 
Thanks a lot!

**Comment by panaaj** [comment]
If you go to Settings and find the __Simulator Starting Values__ section you can specify the starting location (along with other values).

![image](https://user-images.githubusercontent.com/38519157/123893749-2099ad80-d99c-11eb-9e0b-43ce0b4439dd.png)

**Comment by WhyNotPal** [comment]
Hey, 
thanks for your quick reply. 
Yes, I was aware of this section, what I meant is that the values are not taken into account at next start up (on my version at least - V 1.2.0 running on Ubuntu 18.04)
These are the starting values set (should be in the Atlantic, I think):
![image](https://user-images.githubusercontent.com/66071761/123909130-e0750380-d978-11eb-9d02-0ce9f81ce218.png)
This is however the starting position of the ship: 
![image](https://user-images.githubusercontent.com/66071761/123909210-f7b3f100-d978-11eb-9da3-1c54e1b23ab1.png)

Anyway, no drama. Just flagging the issue. 
Have a nice day!

**Comment by panaaj** [comment]
So if I understand correctly, the starting position is saved and displays correctly in the settings screen when the app starts but when you start generating data that start position is not used in the generated data?

**Comment by WhyNotPal** [comment]
> So if I understand correctly, the starting position is saved and displays correctly in the settings screen when the app starts but when you start generating data that start position is not used in the generated data?
yes, exactly

> If you change the starting position and then start generating data does it start at the correct position?
Yes, that works: stop simulation, change coordinates, restart simulation. 
But if I kill the simulator at the new position and relaunch, the simulation starts at Adelaide again.

**Comment by panaaj** [comment]
Thanks..I will look into it

**Comment by panaaj** [comment]
Fix will be in the next release.

**Comment by WhyNotPal** [comment]
Great!! Thanks a lot :-) 
Have a nice day

**Comment by panaaj** [comment]
closed by v1.2.2
