### ISSUE TITLE
tcp server

### ISSUE THREAD

**Issue by JLFra** [panaaj/nmeasimulator#3]
Hello,  could you tell me how to use tcp server. I use a tcp server to read nmea, but not possible to read data on the port. Could you tell me how to use tcp server? thanks

**Comment by panaaj** [comment]
When the TCP Server option is checked NMEASimulator acts as a TCP server transmitting a stream for clients to consume. 
If you telnet to the configured ip address:port you should see the stream of NMEA data.

When the TCP Client option is checked NMEASimulator acts as a TCP client so it can be used to send an NMEA data stream to a server.

Hopefully this clarifies the operation in these modes.

**Comment by panaaj** [comment]
Closed due to inacivity.
