### ISSUE TITLE
GPVTG Sentence

### ISSUE THREAD

**Issue by thend2og** [panaaj/nmeasimulator#30]
Hello, Is there any way where I can put a GPTVG sentence or to activate it inside the program?

https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_VTG.html

I need something like that as I need the speed simulation too. 

Thank you

**Comment by panaaj** [comment]
At this time there is no user selection of sentences to generate.
The is the VTW sentence currently available if that suits.... but I will add VTG in the next release.

**Comment by panaaj** [comment]
closed by v1.2.2
