### ISSUE TITLE
Speed in km/h & mph

### ISSUE THREAD

**Issue by abrowdi** [panaaj/nmeasimulator#31]
Would it be possible to enter the speeds in kilometers per hour and miles per hour? Maybe have a global switch in the settings?

**Comment by panaaj** [comment]
NMEASimulator is designed to provide a NMEA data stream (mostly for testing type use cases) it just uses common units for initiating that stream.
This use case doesn't generally require the need for multplie unit options for setting values.
Can you please provide details of your use case that requires the ability to select units for the "seed" values.

**Comment by abrowdi** [comment]
I am using NMEAsimulator for prototyping an embedded device that will use later a GPS receiver connected via serial. The embeded device will behave differently at certain speeds. This is what I want to test with NMEAsimulator. Those speeds are given in km/h & mph. In NMEAsimulator it is currently only possible to set the helm speed in integer knots. The NMEA RMC message contains the speed in knots with one decimal place. 
It would help a lot if it was possible to 
(A) set the helm speed with this one decimal place (then I could round the mph/kph values to the nearest knots value and do my test) or, even better:
(B) if the helm speed could be set in mph/kph (also with one decimal place) and NMEAsimulator would then round to the nearest knots value and enter it in the RMC message.

**Comment by panaaj** [comment]
At this time I will look to address (A) as it is the least effort and can issue a patch release in a short period of time.

**Comment by panaaj** [comment]
v1.2.3 release addresses this.
