### ISSUE TITLE
Decimal places and rounding of lat/lon coordinates

### ISSUE THREAD

**Issue by Shogun17** [panaaj/nmeasimulator#32]
The latitude and longitude values output in the NMEA strings are being rounded to only 2 decimal places. This results in a very jagged travel path and not a smooth line of travel. Could the output values be changed to use 6 or 8 decimal places instead of 2.

Additionally, there appears to be a rounding error when the value reaches .00 where the decimal part will stay at .00 but the whole part of the number will decrease, and then eventually the decimal will become .99. This results in a pretty large jump of position, and then a jump back. Presumably the whole part and the decimal part are being calculated separately and are getting out of sync (i.e. the whole part is being rounded down, while the decimal part is being rounded up still).

In this example, it goes from 09336.01 to 09336.00 to 09335.00 to 09335.99. The 09335.00 obviously shouldn't be there and should either still be 09336.00 or 09335.99.
[example_GGA_output.txt](https://github.com/panaaj/nmeasimulator/files/7507710/example_GGA_output.txt)

**Comment by panaaj** [comment]
Thanks for raising this issue.
I have been able to reproduce this and will prepare a fix which will be included in the next release.
Additionally the position precision will be increased to 6 decimaal points, this ensures the sentence length does  not exceed the maximum allowed (82 characters including checksum).

**Comment by panaaj** [comment]
closed by v1.3.0
