### ISSUE TITLE
Altitude

### ISSUE THREAD

**Issue by heliraptor66** [panaaj/nmeasimulator#33]
Hi,

Not an issue per say but I was wondering if there is any option available to set an altitude that could be used to simulate an airborne platform?

Secondly having an option to follow a route from an imported .kml file could be useful?

Thanks

**Comment by panaaj** [comment]
Will add following gtrack from KML file using tracks defined by `<gxTrack>` elements.
Also will use the altitude associated with track points (if defined in the imported track data).

I will also look at adding manual control of `altitude` value.
What do you feel would be a suitable value range for alitude 0 -10000m in 200m steps?

**Comment by heliraptor66** [comment]
That's great,

Would that pull in altitude from a GPX track as well?

As for the range, I probably only need it up to 10000 feet (3048m), steps of 50' (15.24m) would be the most useful but others may want the larger altitude range.  It really depends what your limitations are.

I've added a .gpx file below that should contain altitude for test purposes.

[Scotland-1.gpx.zip](https://github.com/panaaj/nmeasimulator/files/7618775/Scotland-1.gpx.zip)

**Comment by panaaj** [comment]
Yes altitude will also be used from GPX files.

**Comment by panaaj** [comment]
closed by v1.3.0
