### ISSUE TITLE
Click to position vessel does not work

### ISSUE THREAD

**Issue by speters** [panaaj/nmeasimulator#34]
Setting the vessel position by clicking on the map as indicated by the "Clip to position vessel" hint does not work.

To reproduce:
 * NMEASimulator-1.2.3.AppImage on Arch Linux x86_64
 * Start position is set via settings tab to 54N,010E. (any position will do)
 * Vessel position now at 54N,010E
 * Start simulation, vessel moves
 * Click on map
 * Vessel gets positioned at 0,0.
 * Stop simulation
 * Click anywhere on map
 * Vessel gets positioned at 0,0
 * Reset to start values correctly resets vessel to the position given in the settings tab

Expected behaviour:
 * Clicking on map sets vessel to position as indicated by the "Click to position vessel" hint
 * Accidental resetting vessel position during simulation should be avoided - maybe only reposition while stopped.

Additiomal info:
When starting the AppImage, the following message is shown:
 > (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check `https://github.com/electron/electron/issues/18397`
 
Screen recording of map area:
[MP4, 320x240, 165kB, no audio](https://user-images.githubusercontent.com/1384994/144236948-1f6f1bce-be48-4283-8518-2cd2b88e75f3.mp4)

**Comment by panaaj** [comment]
A fix for clicking on the map will be included in the next release.

As for the startup message, this is an information message related to a runtime configuration that must stay in place for the meantime due to a 3rd party library not yet being able to accommodate the setting.
This will be addressed once the library has been upgraded.

**Comment by panaaj** [comment]
closed by v1.3.0
