### ISSUE TITLE
"Override" does not initialize manual setting

### ISSUE THREAD

**Issue by speters** [panaaj/nmeasimulator#35]
Thank you for this great tool!

####  Problem:
Clicking "override" on a gauge does not seem to initialize the manual setting.

#### Version:
 1.3.0 (maybe also earlier)

####  Reproduce:
  * click "Override" on a gauge to enable
  * first click on"+" or "-" moves slider to the left, but does not adjust value
  * subsequent clicks on "+" or "-" have no effect
  * move the slider: value of slider is set
  * click "+" or "-" now adjusts value

#### Expected:
 * after enabling "Override" subsequent clicks on "+" or "-" should have immediate effect
 * slider should either
     * cover the whole range of possible values (absolute) and be synced to the gauge, or
     * act as a jog to adjust relatively depending on how far it is moved from its middle position; in this case it only adjusts while being held and moves back to its middle position as soon as it is released (relative value taken on release)
  * double click/tap on value should offer input as value

It looks like there is a similar issue with the GPS PDOP, HDOP, etc. overrides.

###### PS:
Clicking on map should not move vessel while simulation is running.
For convenience, double-clicking/tap on the "marked position" values could adjust vessel position to marked position.
Values should be copied to clipboard (on click/tap?).
It should be possible to select/copy text (notably the NMEA output).
Rearranging gauges/outputs does not seem to give easy results (at least on my rather smallish 1400x900 screen).

**Comment by panaaj** [comment]
I was not able reproduce the issue exactly as you described it, but I did identify an issue with the control to manually adjust values.

**Comment by panaaj** [comment]
issue closed by v1.3.1
