### ISSUE TITLE
Web Socket "Upgrade Required" Message

### ISSUE THREAD

**Issue by ataxia1** [panaaj/nmeasimulator#36]
When configured to generate sentences via Web Socket, the only data that seems to come through is an "Upgrade Required" message.

A screenshot of my selected settings is attached.

![NMEASimulator](https://user-images.githubusercontent.com/36685943/148117224-b729494b-f8fc-4609-90cc-d04e078a0fea.png)

**Comment by panaaj** [comment]
I cannot reproduce an issue using websockets.
Can you pease advise which version of the app and the client type (linux, win, mac, RPi) you are using and your setup which is producing the error.

**Comment by ataxia1** [comment]
Hi, thanks for writing back.  1.3.1 on a PC.  Web socket on port 3000, NMEA output stream format.  Works fine in TCP mode.

**Comment by panaaj** [comment]
So a PC using Windows or Linux?
Where is the  "Upgrade Required" message appearing, in the client connecting to the stream?
How are you connecting to the websocket stream?
Can you provide a screenshot of the error?

**Comment by ataxia1** [comment]
Sorry, thought Windows was implied by PC, but you got me there.. could have been running Linux.

Windows 10 64 bit.

Just figured out the problem.  Was testing with Postman, and there is a separate way you have to set up a web socket GET request versus an HTTP GET.  Sorry to waste your time, but I really appreciate you trying to help me out.   You made a great program.




________________________________

**Comment by ataxia1** [comment]
Turns out to be an issue with how I was testing, not with the simulator.  Closing the ticket.   For those using Postman, be sure to create a Web Socket project instead of an HTTP project.
