### ISSUE TITLE
How to use UDP

### ISSUE THREAD

**Issue by DenisIvanovIvanov** [panaaj/nmeasimulator#37]
Is there a way to listen for messages from the simulator through UDP? If so, how?

**Comment by panaaj** [comment]
UDP is not currently supported.

**Comment by patrickelectric** [comment]
Where is the source code ? Can you add support to udp ?

**Comment by panaaj** [comment]
UDP support is planned and will be available in a future release.

**Comment by panaaj** [comment]
@patrickelectric A pre-release with Initial support for UDP can be found [here](https://github.com/panaaj/nmeasimulator/blob/udp/release/NMEASimulator-1.4.0-udp.AppImage) if you want to try it and see if it addresses your needs.

**Comment by patrickelectric** [comment]
> A pre-release with Initial support for UDP can be found [here](https://github.com/panaaj/nmeasimulator/blob/udp/release/NMEASimulator-1.4.0-udp.AppImage) if you want to try it and see if it addresses your needs.

Can you add the functionality to work as a UDP client, to a desirable IP / port ?

**Comment by panaaj** [comment]
Updated to include `UDP Client` option that allows target IP and port to be defined.
