### ISSUE TITLE
Replay gpx speed issue

### ISSUE THREAD

**Issue by DrZ1o** [panaaj/nmeasimulator#39]
When replaying a file from Garmin gps, despite of the speed override flag the speed being sent to UART is the set speed, not a gpx log speed.

**Comment by panaaj** [comment]
Can you please provide a copy of the file for me to test.

**Comment by DrZ1o** [comment]
I assumed speed to be calculated from a distance between waypoints over time stamps.

Here is an example of the track I have been following:
https://drive.google.com/file/d/10fd9I8w6fgBkdFk-Ru6xknc3PMIcEPIl/view?usp=drivesdk

**Comment by DrZ1o** [comment]
https://drive.google.com/file/d/1CX7_I0DpogOPLnDsssd6_s-28FC1fMz_/view?usp=drivesdk

This file is an example of the real log.
I have been using Nmea simulator to test a GPS device at various speeds and had to override and set the speed manually.
🙂

**Comment by panaaj** [comment]
Feature is included in v1.4.0
