### ISSUE TITLE
DPT telegram simulation is incomplete. 

### ISSUE THREAD

**Issue by MCS-Tech** [panaaj/nmeasimulator#4]
Hi,
Thanks for a promising tool!
I have found that the simulation of the DPT telegram is not compliant with the 0183 standard.
It should consist of two values and a checksum. I believe you are missing one comma before the checksum?

Cheers!

DPT Heading – Deviation & Variation
$--DPT,x.x,x.x*hh
1) Depth, meters
2) Offset from transducer;
 positive means distance from transducer to water line,
 negative means distance from transducer to keel
3) Checksum

**Comment by panaaj** [comment]
I cannot replicate the issue you have raised...when transmitting a data stream this is the output generated: which does in fact have both the depth and the offset.

![image](https://user-images.githubusercontent.com/38519157/81028637-74585600-8ec1-11ea-9078-1ee886e607fb.png)

At the client, this is the data received:

![image](https://user-images.githubusercontent.com/38519157/81028810-0ceed600-8ec2-11ea-9a40-c281697feffe.png)

Can you please clarify where / how you are encountering the issue.

**Comment by MCS-Tech** [comment]
Hi,
Sorry for late reply. I see I was a bit unclear in my initial comment. 
The mistake I believe is that you are sending a leading zero. Offset value "01".

The value is numeric, and at least our equipment does not interpret leading zeros in any sensible way.

I think 1 meter offset should be sent as 1.0 or 1. Not as "01".

**Comment by panaaj** [comment]
Thanks for clarifying the issue... I have corrected this value so it will be fixed in the next release.

**Comment by panaaj** [comment]
Fixed in v1.0.0
