### ISSUE TITLE
Baud Rate for serial port is not customizable

### ISSUE THREAD

**Issue by TheMaakarov** [panaaj/nmeasimulator#41]
This is actually a request more than an issue.
I'm trying to output to a COM port but the device connected to it has a Baud Rate different than any of those shown in the dropbox:
![image](https://user-images.githubusercontent.com/39929306/180168351-00299b6b-a5de-47cb-bbeb-c47675d45bd1.png)
![image](https://user-images.githubusercontent.com/39929306/180168423-17c9d677-1eb5-4a6b-9927-68c40c2a57c7.png)

**Comment by panaaj** [comment]
The common buad rates are supported (110, 300, 1200, 2400, 4800, 9600, 14400, 19200, 38400, 57600, 115200) as there are no guarantees a platform will support custom rates.
Your need to use a custom rate, is that due to the device not supporting a common rate?

**Comment by panaaj** [comment]
Feature is included in v1.4.0
