### ISSUE TITLE
NMEA Sentence

### ISSUE THREAD

**Issue by denizci88** [panaaj/nmeasimulator#43]
Hello,

First of all thank you for this great tool. I would like to inform about an issue. I have reviewed the NMEA sentences and found two sentences, as follows.

$SDDBK,44.9,f,13.7,M,7.5,F*17
$SDDBS,44.9,f,13.7,M,7.5,F*0F

When I checked IEC 61162-1 standard, I noticed that DBK and DBS are not available. Hopefully, you don't consider my message as a negative comment, and would accept it as a support to your great tool. Thank you again.

Wishing you a fun summer!

**Comment by panaaj** [comment]
You are correct these are deprecated sentences.
These are emitted to address the requirement to support legacy equipment and will likely be removed in future versions
DPT and DBT sentences are also emitted.

**Comment by denizci88** [comment]
Thank you for your reply. DPT and DBT are still in the standard.
