### ISSUE TITLE
Edit Talker IDs or sentence structure

### ISSUE THREAD

**Issue by Beard81** [panaaj/nmeasimulator#45]
Ho, I love this program, it's what I need except the II talker ID for VHW does work for my application. Im wondering if it's possible to edit the talker ID of certain sentences?

**Comment by panaaj** [comment]
Not currently a feature but can be considered.
Technically the talker ID should not matter, the NMEA spec does not make any reference to sentences being tied to specific talker IDs.
That said, what talker id would be considered valid by your application?

**Comment by MCS-Tech** [comment]
Hi,

If it is not too much hassle I would suggest adding an option for changing the ID for all talkers,
Not sure if this is up to date, but this is a list of Talker-IDs as of March 2019: 

https://www.nmea.org/Assets/20190303%20nmea%200183%20talker%20identifier%20mnemonics.pdf

Sometimes, during simulation testing, it is needed to be able to specify a given talker. Especially if one is testing a listener device which is expecting a specific talker ID to be used.

Cheers!

**Comment by Beard81** [comment]
I'm playing with users that require the IN talker ID.  I do agree though, many systems ignore the talker ID all together, but it would be nice to edit the text or have all options of talker ID as mentioned above

**Comment by panaaj** [comment]
v1.4.1 release allows talker id to be defined.
