### ISSUE TITLE
Raspberry Pi 64bit OS

### ISSUE THREAD

**Issue by jft7** [panaaj/nmeasimulator#46]
Do you have any plan for building a Raspberry Pi 64bits image ?

**Comment by panaaj** [comment]
Not specifically planning to target 64bit at this time.
It would only be considered if it was required for the appllication to work on the platform.

**Comment by jft7** [comment]
Thanks
Your simulator is really excellent and very useful.
We use it on Pi4 but we recently moved our applications to 64bits Pi OS due to performance improvement. We'll have to use a separate computer for running the simulator but it's not a big problem (just comfort ...)
