### ISSUE TITLE
Feature Additions?

### ISSUE THREAD

**Issue by Beard81** [panaaj/nmeasimulator#47]
I love your program, but I'm hoping you can add a couple features;

1. Can you add the ability to output NMEA data on different COM/TCP/UDP ports?  I'm simulating to a device that receives data via different inputs.
2. Can you add the option to manually enter a NMEA sentence?  I have some proprietary messages I'd like to output.
3. I noticed when I choose UDP port there is no option for entering the Multicast IP Address.  Can this be added?

Also, could you add TTM and VBW sentence IDs?

Thanks!

**Comment by panaaj** [comment]
> 1. Can you add the ability to output NMEA data on different COM/TCP/UDP ports?  I'm simulating to a device that receives data via different inputs.

By this do you mean more than one channel simultaneously?
i.e. nmea stream is transmitted on both COM5 and TCP port 3100

**Comment by panaaj** [comment]
> 2\. Can you add the option to manually enter a NMEA sentence?  I have some proprietary messages I'd like to output.

I will add this to the backlog.

**Comment by panaaj** [comment]
> Also, could you add TTM and VBW sentence IDs?

I have no problem including the VBW sentence in future.
As for TTM I will consider this, the implementation needs to be meaningful and will require more effort.

**Comment by Beard81** [comment]
By this do you mean more than one channel simultaneously?
i.e. nmea stream is transmitted on both COM5 and TCP port 3100

Yes exactly, or multiple com ports.

**Comment by Beard81** [comment]
I have no problem including the VBW sentence in future.
As for TTM I will consider this, the implementation needs to be meaningful and will require more effort.

Thank you, TTM is a nice to have for my simulations...

**Comment by Beard81** [comment]
Hi, just wondering if you are still planning to perform the enhancements mentioned above. Happy Holidays.

**Comment by panaaj** [comment]
Yes I am... just very time poor at the moment.
Hopefully in the next week.

**Comment by panaaj** [comment]
Found some time today and created v1.4.2 release which addresses support for manually adding NMEA sentences and emitting VBW sentence.
Something is better than nothing I hope!

Multicast support will not happen for a while... sorry but it's still on the list.

**Comment by Beard81** [comment]
That's great, thank you for addressing this. I look forward to playing around with it when I'm back from vacation!

**Comment by Nemos** [comment]
if i am not wrong it seems there is a bug on 1.5.0 version as the udp client or broadcast doesn't work.

**Comment by panaaj** [comment]
Multicast is supported in v1.6.0
