### ISSUE TITLE
Boat Control through command line ? 

### ISSUE THREAD

**Issue by d2snc** [panaaj/nmeasimulator#48]
Hello, I really liked the program and it is very useful for me, I am developing a control system for a speedboat and I would like to know if it would be possible to enter commands for the ship in the nmea simulator through the command line or another method? Increase propulsion for example.

Thanks in advance !

**Comment by panaaj** [comment]
When you say "enter commands" I assume that means whilst the app is running and not just at launch?
Currently the only method is to interact via the GUI controls or use keyboard arrow keys for port /starboard (steering mode) and faster / slower (when manual override is selected for speed).

**Comment by d2snc** [comment]
Yes, it would be with the program running, basically the control system would calculate a rudder angle and machine intensity for the ship according to the waypoint we want to go, hence the idea of ​​sending the commands through a line would be very interesting command, for example "SB10" as being a 10 degree starboard yaw. Just a suggestion, thanks for the reply!
