### ISSUE TITLE
Image for Raspberry Pi

### ISSUE THREAD

**Issue by 1orogue** [panaaj/nmeasimulator#5]
Hello sir,

I have been looking at various NMEA simulators and wanted to use yours, but I can see you don't have an image for Raspberry Pi.
Do you know if this will be a future thing?

Kind regards

**Comment by panaaj** [comment]
I have only briefly investigated creating a RPi image. I have created a runnable image but there were some significant screen rendering issues and not suitable for release.

As the inital focus is to have a replacement for the soon to be unsupported Chrome App, the plan is to have something for the RPi but not part of the inital release. 

Hopefully this answers your question.

**Comment by panaaj** [comment]
@1orogue release v1.0.0 has an armv7l Appiimage for the Rasperry Pi.
