### ISSUE TITLE
32-bit version?

### ISSUE THREAD

**Issue by Beard81** [panaaj/nmeasimulator#50]
Is it possible to create a 32 bit version of the application?

**Comment by panaaj** [comment]
For which platform?

**Comment by Beard81** [comment]
Windows 7

**Comment by panaaj** [comment]
It's not a platform I can test so any build would be not guaranteed.
Also is the effort worthwhile?
I accept there are use cases out there but additional platforms increase build time / effort.

**Comment by Beard81** [comment]
Understood, it's convenient for my application as I use a specific 32-bit platform for mobile applicatons. If it's not worth the effort overall, no problem.
