### ISSUE TITLE
Empty window after installation the nmeasimulator_1.4.2_amd64.deb

### ISSUE THREAD

**Issue by IvanZOnGitHub** [panaaj/nmeasimulator#53]
**This is the result when I start:**
![image](https://user-images.githubusercontent.com/130861339/232246914-565a0f46-6c08-44b4-9b92-c0a63f6394ab.png)

**This is the installation LOG:**
ivanz@laptop:~/Downloads$ sudo apt install /home/ivanz/Downloads/nmeasimulator_1.4.2_amd64.deb 
[sudo] password for ivanz: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'nmeasimulator' instead of '/home/ivanz/Downloads/nmeasimulator_1.4.2_amd64.deb'
The following packages were automatically installed and are no longer required:
  gir1.2-goa-1.0 gir1.2-snapd-1
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  nmeasimulator
0 upgraded, 1 newly installed, 0 to remove and 35 not upgraded.
Need to get 0 B/137 MB of archives.
After this operation, 2.950 MB of additional disk space will be used.
Get:1 /home/ivanz/Downloads/nmeasimulator_1.4.2_amd64.deb nmeasimulator amd64 1.4.2 [137 MB]
Selecting previously unselected package nmeasimulator.
(Reading database ... 186687 files and directories currently installed.)
Preparing to unpack .../nmeasimulator_1.4.2_amd64.deb ...
Unpacking nmeasimulator (1.4.2) ...
Setting up nmeasimulator (1.4.2) ...
Could not parse file "/usr/share/applications/openoffice4-draw.desktop": No such file or directory
Could not parse file "/usr/share/applications/openoffice4-calc.desktop": No such file or directory
Could not parse file "/usr/share/applications/openoffice4-javafilter.desktop": No such file or directory
Could not parse file "/usr/share/applications/openoffice4-math.desktop": No such file or directory
Could not parse file "/usr/share/applications/openoffice4-writer.desktop": No such file or directory
Could not parse file "/usr/share/applications/openoffice4-startcenter.desktop": No such file or directory
Could not parse file "/usr/share/applications/openoffice4-printeradmin.desktop": No such file or directory
Could not parse file "/usr/share/applications/openoffice4-base.desktop": No such file or directory
Could not parse file "/usr/share/applications/openoffice4-impress.desktop": No such file or directory
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...

**Comment by panaaj** [comment]
I have tried to reproduce the issue without success  (Linux Mint 21.1 based on Ubuntu Jammy).
Not sure where the references to openoffice are coming from as they are not part of the NMEASimulator package.

**Comment by IvanZOnGitHub** [comment]
Hi, thank you for the prompt reply!
Can this be the case that you are using Qt6. Because there are some issues with Ubuntu 18.04 and Qt6.
And if yes, is it possible to provide the packages of the previous versions.
Thanks again,
Ivan

**Comment by panaaj** [comment]
Possibly. All OS packages are built with `electron-builder`.
Sorry, but the only packages available are those in `releases`.
You might want to try one of the earlier version to see if you get a different result.

**Comment by IvanZOnGitHub** [comment]
Hi, just for info... I tried many previous versions and I can see that the last working image is
nmeasimulator_1.2.2_amd64.deb.
I am still on Ubuntu VERSION="18.04.6 LTS (Bionic Beaver)"
Nevertheless! Very nice simulator and I like it much!
