### ISSUE TITLE
A new usefull feature

### ISSUE THREAD

**Issue by eirasys** [panaaj/nmeasimulator#54]
Adrian
Hello,
I was looking for a way to update google earth GPS location in realtime, synced with a KMZ file, or even better, a SRT file and
I found your app!
My goal is to play a mp4 DIJ drone video (in Mac) and simultaneously read it's SRT file and send it to GoogleEarth Pro as
NMEA data or GARMIN PVT (the available options).
Is it possible to do?
This way it would be possible to play the drone footage in realtime while watching it's position and elevation in google earth!
It will make great success if possible. I can help, have some programming skills.
João

**Comment by panaaj** [comment]
What you describe would be possible using ViewSynch to control Google Earth(tm) displays.

Whilst NMEASimulator does send ViewSynch messages, but your use case seems more suited to its own app.

**Comment by eirasys** [comment]
Thanks.
Anyway I tried several times the NMEASimulator but could not control the GoogleEarth Pro GPS position.
I may be doing something wrong. I will try the Earth Engine using JavaScript.
