### ISSUE TITLE
Signal K server address

### ISSUE THREAD

**Issue by bmansion** [panaaj/nmeasimulator#55]
Thanks for your very useful simulator!
I am trying to simulate Signal K data on my Mac, and access the json objects from safari.
What would be the http address?
I tried this: 

https://my.IP.address/signalk/v1/api/vessels/urn:mrn:signalk:uuid:b7590868-1d62-47d9-989c-32321b349fb9/navigation/trip/log/value/

Here is my settings:
<img width="842" alt="Capture d’écran 2023-05-11 à 10 29 14" src="https://github.com/panaaj/nmeasimulator/assets/133206477/c8a23bdb-fb5c-435a-8830-116041389dd6">

But it doesn't work
Sorry I am not a developper but a newbie...
Thanks!

**Comment by panaaj** [comment]
If you are aiming to use Safari to view the data stream you will need to choose websocket.

**Comment by bmansion** [comment]
Thanks for your reply.
I tried with websocket, but with no luck...
Is this address correct? https://my.ip.address/signalk/v1/api/vessels/urn:mrn:signalk:uuid:b7590868-1d62-47d9-989c-32321b349fb9/navigation/trip/log/value/

**Comment by panaaj** [comment]
To connect to websocket served by NMEASimulator, you need to connect using ws://nneasimulator-ip-address:port

**Comment by bmansion** [comment]
Progress: now I can access the page, but it says "Upgrade Required"...
Thank you!

**Comment by panaaj** [comment]
You CANNOT connect to websockets by entering `ipaddress:port` the browser location  bar... this will issue an http request and you will get the "Upgrade required" message.

To make a websocket connection, you will need to either: 
- Write some Javascript code
- Or use a websocket client such as the "Simple Websocket Client" Chrome extension.

![image](https://github.com/panaaj/nmeasimulator/assets/38519157/56513ffc-5353-4003-9413-cc5888a82c13)

Alternatively you can view the stream in a Terminal window by selecting **TCP Server** in NMEASimulator setting and using `telnet`.

`user@host:~$ telnet ipaddress port`
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"name":"nmea-simulator","version":"17.12.05","self":"vessels.urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d","roles":["master","main"],"timestamp":"2023-05-12T23:09:59.467Z"}{"context":"vessels.urn:mrn:signalk:uuid:c0d79334-4e25-4245-8892-54e8ccc8021d","updates":[{"timestamp":"2023-05-12T23:09:59.946Z","$source":"nmea-simulator","values":[{"path":"navigation.courseOverGroundTrue","value":0.2153830042413598},{"path":"navigation.headingTrue","value":0.2153830042413598},{"path":"navigation.speedOverGround","value":2.5722162730222498},{"path":"navigation.speedThroughWater","value":2.5722162730222498},{"path":"navigation.gnss.horizontalDilution","value":1.9661940150000004},{"path":"navigation.gnss.positionDilution","value":2.577279269747881},{"path":"navigation.gnss.satellites","value":4},{"path":"navigation.gnss.methodQuality","value":"GNSS Fix"},{"path":"navigation.gnss.type","value":"GPS"},{"path":"navigation.position","value":{"longitude":151.5000885254437,"latitude":-38.999726837696194,"altitude":250}},{"path":"environment.wind.directionTrue","value":5.484042675922685},{"path":"environment.wind.speedTrue","value":1.8951460559229227},{"path":"environment.wind.angleApparent","value":-0.423228992611129},{"path":"environment.wind.speedApparent","value":3.9186487361239117},{"path":"environment.water.temperature","value":280.50222037055187},{"path":"environment.depth.belowTransducer","value":6.581619798335055},{"path":"propulsion.p0.state","value":"stopped"},{"path":"propulsion.p0.label","value":"Port Engine"},{"path":"propulsion.p0.temperature","value":361.60134085},{"path":"propulsion.p0.revolutions","value":0},{"path":"propulsion.p1.state","value":"stopped"},{"path":"propulsion.p1.label","value":"Starboard Engine"},{"path":"propulsion.p1.temperature","value":365.1928199783868},{"path":"propulsion.p1.revolutions","value":0}]}]}
```

**Comment by panaaj** [comment]
Issue closed.

**Comment by bmansion** [comment]
thank you very much!
