### ISSUE TITLE
UDP client / Broadcast doesn't work

### ISSUE THREAD

**Issue by Nemos** [panaaj/nmeasimulator#56]
If i am not wrong it seems there is a bug on 1.5.0 version  (tested to 1.4.2 as well) as the udp client or broadcast doesn't work.
The UDP server does not receive anything in addition I have check the network traffic and the NMEA simulation doesn't send anything to the network. 
NMEA 1.4.2 installed in Linux ubuntu 20.04 64

**Comment by panaaj** [comment]
I could not reproduce the issue.
v1.6.0 does contains updates to support multicast and UDP broadcast interface so please try and see if this fixes your issue.
