### ISSUE TITLE
Marine traffic GPX route 

### ISSUE THREAD

**Issue by Ittech-tanker** [panaaj/nmeasimulator#59]
Hi mr adrian

Is it possible to load marine traffic website route (gpx) on the nmeasimulator and simulate the ship movement?

Or convert the marine traffic gpx to Google gpx?

**Comment by panaaj** [comment]
You can load a GPX file containing track(s).
As NMEASimulator advances one point every interval, as route points are generally fewer in number and further apart, it has not been considered as a use case at this time.

I will consider it as a feature if others deem it useful.

**Comment by Ittech-tanker** [comment]
Thank dear mr adrian

It will be great if you add this feature.

Because the marine traffic website offers vessel route planning with more detail and then you can save it as a gpx file.


Is there any way to request for a private use case?

**Comment by panaaj** [comment]
I will add it to the backlog for the next release.

**Comment by Ittech-tanker** [comment]
That is nice, thanks in advance Mr adrian
Any schedule for the next release?

**Comment by panaaj** [comment]
v1.6.1 is now available.
