### ISSUE TITLE
TCP server output interval

### ISSUE THREAD

**Issue by MaxCarritt** [panaaj/nmeasimulator#6]
Hi, the output interval other than 1000ms doesn't seem to work. I tried setting it to 5000ms and it stops working. Also I wasn't able to connect to the Mac OS tcp server at all, I ran it on a windows machine and that worked.

**Comment by panaaj** [comment]
As there are two issues mentioned here i will address them separately:

1. `I wasn't able to connect to the Mac OS tcp server`: You will need to ensure that your device (whatever OS) is allowing incoming connections to the IP address NMEASimulator is attached to. So if prompted you should allow connections.
![allow](https://user-images.githubusercontent.com/38519157/82395161-12374d80-9a8a-11ea-8d69-a2498ba511db.jpeg)

2. `output interval other than 1000ms doesn't seem to work`: I have tried and cannot reproduce output stopping at any interval setting. Can you please provide some details of what steps caused the output to stop.

**Comment by MaxCarritt** [comment]
1. I allowed it. Even locally I tried netcat in terminal to connect, and it connects but I dont get any output. 

2. Hrm, I played around with it a bit more and it seems like I have to close and re-open the program to get it to register the new setting. If I stop it, change the interval, then start it again, I dont get anymore data until I restart the program completely.

**Comment by danderer** [comment]
I saw some intermittent behavior on macOS also.  Would transmit, then wouldn't.  Seemed to fail when I was playing back a GPX file though frankly I didn't test that extensively.  Will test more as time permits.

By the way - great project!

**Comment by panaaj** [comment]
You mentioned bot Windows and MacOS in the original post.... do you see the same behaviour on both or just MacOS?

**Comment by danderer** [comment]
> I saw some intermittent behavior on macOS also. Would transmit, then wouldn't. Seemed to fail when I was playing back a GPX file though frankly I didn't test that extensively. Will test more as time permits.
> 
> By the way - great project!

Can't reproduce.  Figures.
