### ISSUE TITLE
no changes of nmea values at the com port

### ISSUE THREAD

**Issue by MDeTL** [panaaj/nmeasimulator#60]
I have a problem with the nmea values on the com port. If I change a value like the vessel speed I can see that the value has changed in the NMEA Output window. But the real output on the com port has not changed. 
I used two USB to RS422 adapter to test the output and used hterm to log the transmitted data from the simulator.

I also tested different output intervals but doesn't help.

Baud: 4800
Parity: none
Data bits: 8
Stop bits: 1

Have I set something wrong or is it a bug?

**Comment by panaaj** [comment]
I cannot reproduce the issue you describe.
I have checked comport output as well as other output channels and the data seen in those streams reflects that shown in the Output window.

I see the correct speed reflected in RMC, VHW & VTG sentences.

**Comment by MDeTL** [comment]
Sorry I have written the vessel speed but I mean the engine rpm.
If I disable gps, wind, destination and water then is the output much faster.

**Comment by panaaj** [comment]
From what I can see the RPM values are changing.
v1.6.1 contains some "tweaking" of the output stream written to serial port which should hopefully address variance in output transmission.
