### ISSUE TITLE
v1.6 vs 1.5

### ISSUE THREAD

**Issue by AndrasSzep** [panaaj/nmeasimulator#61]
I have an [application](https://github.com/AndrasSzep/NMEA0183-to-NMEA2000) working fine on the previous versions (e.g. 1.5 both Linux and Mac) which on the new version only catches the first set of NMEA0183 sentences after starting the simulator (UDP broadcasting mode). Stoping/resuming the simulator does not help. Only complete restart of the program.

**Comment by panaaj** [comment]
The main difference in version 1.6 is that:
1. You can select the network interface
2. The broadcast address is calculated based on the interface configuration.

When I test on a client device using **netcat** with the command _nc -kluvw 0 <port_number>_
I see the changing stream of broadcast data.

I assume when you say restart the program you are referring to your application?

**Comment by AndrasSzep** [comment]
I mean restarting your simulator. The bug shall be in the simulator.
