### ISSUE TITLE
Simulate Fast Packet?

### ISSUE THREAD

**Issue by jeokeefe** [panaaj/nmeasimulator#62]
Is there a way to simulate "Fast Packet" which typically has 10-12 frames of data (not 8)?

**Comment by panaaj** [comment]
Are you referring to NMEA2000 fast packet?

**Comment by jeokeefe** [comment]
Hi, Yes, NMEA 2000 "Fast Packets." I should rephrase the question... Is the simulator simulating "fast packets"? This would apply to engine data.

**Comment by panaaj** [comment]
No it is not simulating fast packets.

**Comment by jeokeefe** [comment]
Thank you
