### ISSUE TITLE
Custom Sentences

### ISSUE THREAD

**Issue by jeokeefe** [panaaj/nmeasimulator#63]
I am trying to broadcast the following sentence in the "Enter Sentence" Widget. I stop the simulator, enter the data, click apply, and press play. The message does NOT appear in the candump of the network. Is my format incorrect??

01FF04FF [8] E0 17 A3 99 04 80 05 02

**Comment by panaaj** [comment]
The software only supports NMEA0183 and Signal K output.

As it looks like you are entering a NMEA2000 PGN it will not be transmitted.

What is your use case?

**Comment by jeokeefe** [comment]
Oh, that makes sense. I am using it as an NMEA 2000 simulator for a software development project. I am using the YDNU-02; it must convert the NMEA0183 data to NMEA 2000, as everything I see on the network is N2k. Do you have any suggestions for a solution that will transmit NMEa2k?

**Comment by panaaj** [comment]
Sorry I don't.
