### ISSUE TITLE
Serial port is not enabled

### ISSUE THREAD

**Issue by momomanta** [panaaj/nmeasimulator#64]
![image](https://github.com/panaaj/nmeasimulator/assets/163289320/a120c2b7-a1e2-4cf2-b824-254fd67ff675)

Hi I am using windows 11 and serial port is not enabled.
Can someone help me to identify the issue ? I have tried with windows 10 and 7 as well with no success.

**Comment by panaaj** [comment]
What type of serial port is it... USB device, built-in?

There is the option to enter the serial port manually.

**Comment by momomanta** [comment]
Hi, It is solved. It was the problem of driver with serial port. It was built in USB port.
Thanks :)
