### ISSUE TITLE
Simulating course change

### ISSUE THREAD

**Issue by sailcs33** [panaaj/nmeasimulator#65]
I am trying to use the simulator to change course from 50 deg to 60 deg. Would this be correct syntax?

$AGAPB,A,A,0.10,R,N,A,A,011,M,DEST,50,M,60,M*7F

**Comment by panaaj** [comment]
With the simulator running you can "right click" on the map and this will populate the APB and RMB sentences.
Click again on a different location to change the destination.
This would be the simplest way.
