### ISSUE TITLE
Limiting Messages

### ISSUE THREAD

**Issue by mattalanskas** [panaaj/nmeasimulator#68]
Is there a way to not output every message on the settings page?

**Comment by panaaj** [comment]
You can "mute" messages coming from the various groups on the dashboard e.g. wind by clicking the mute button in that section.

**Comment by mattalanskas** [comment]
Reopening for one more question. I have muted everything I believe and am getting this output.

$GNRMC,175557.602,A,3754.410129,N,12255.776480,W,32.2,295.4,131224,,,*1C
$IIVHW,295.4,T,295.4,M,32.2,N,59.7,K*5D
$IIVTG,295.4,T,295.4,M,32.2,N,59.7,K*51
$IIHDT,295.4,T*28
$GPGLL,3754.410129,N,12255.776480,W,175557.602,A*27
$GPGGA,175557.602,3754.410129,N,12255.776480,W,1,4,1.2,2.0,M,,,,*29
$GPGSA,A,3,8,11,15,22,,,,,,,,,0.8,1.2,4.1*00
$GPZDA,175557.602,13,12,2024,-08,00*76
$IIVBW,31.4,31.7,A,31.6,31.7,A,31.3,A,32.0,A*41
!AIVDO,1,1,,A,17PaewhP52o=AMpEd<9KRI?j0000,0*31
!AIVDM,1,1,,A,17PaewhP52o=AMpEd<9KRI?j0000,0*33
$INWPL,3754.709573,N,12255.795242,W,wpt*3E
$IIAPB,A,A,-0.229175,L,N,,,291.0,T,dest,291.1,T,291.1,T,A*73
$GPRMB,A,-0.229175,L,origin,dest,3858.788931,N,12642.936960,E,189.316,291.1,32.1,,A*0D

I really only need RMC and GGA. Is there a way to get rid of the rest? I do not really see a method of doing so but was wondering if this could be implemented because it seems the data output is lagging due to the amount of messages being transmitted. The output NMEA log and the input of my UART port on my MCU is not lining up
