### ISSUE TITLE
GPZDA contains a + leading the positive timezone

### ISSUE THREAD

**Issue by Laro88** [panaaj/nmeasimulator#7]
At least one major gps library has a hickup over this, and my implementation also got hit by this. Any chance you can leave out the leading + when it is positive.

This is the NMEA spec for ZDA
![image](https://user-images.githubusercontent.com/12495700/87307126-5a6a6d80-c519-11ea-9256-ba507600ea0a.png)

**Comment by panaaj** [comment]
Fix created.. release 1.0.1 will include this

**Comment by panaaj** [comment]
v1.0.1 released
