### ISSUE TITLE
/dev/ttySC0 and /dev/ttySC1 not available on Raspberry PI

### ISSUE THREAD

**Issue by andyrbarrow** [panaaj/nmeasimulator#8]
I have a RS485 hat that is used for NMEA0183 on my Raspberry PI. It has two interfaces that come into the RPI via the SPI interface, and they appear as /dev/ttySC0 and /dev/ttySC1. I can connect to them with minicom and send/receive ASCII characters. 

When I run the nmeasimulator appimage, the settings app does not give me an option to use these devices. I only have the option of using of using /dev/ttyACM0 (one of my USB connections).

Awesome application - I used it extensively when it was a Chrome Extension. I'm excited that it now runs as a stand-alone app.

**Comment by panaaj** [comment]
The SerialPort list is filtered to only include devices that have at least one of the following properties:

- pnpId
- vendorId
- productId
- locationId.

This is to try and stop listing devices that are not serial ports.

**Comment by andyrbarrow** [comment]
Okay, thanks. Perhaps in a future release it might be possible just to allow an "Other" selection with the ability to type into a text box?

**Comment by panaaj** [comment]
resolved in [v1.0.2](https://github.com/panaaj/nmeasimulator/releases/tag/v1.0.2https://github.com/panaaj/nmeasimulator/releases/tag/v1.0.2)
