### ISSUE TITLE
Desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [panaaj/nmeasimulator#9]
Desktop file does not pass desktop-file-validate:

> nmeasimulator.desktop: error: file contains key "Description" in group "Desktop Entry", but keys extending the format should start with "X-"

Can you please fix it and provide a fixed AppImage? Thank you very much :+1: 

Reference:
https://github.com/AppImage/appimage.github.io/pull/2160

**Comment by panaaj** [comment]
@probonopd can you please provide some more detail on this error as the AppImage published works fine on Debian as does the arm Appimage for RPi.

**Comment by probonopd** [comment]
Hi @panaaj thanks for making an AppImage and for responding here.

The file `nmeasimulator.desktop` has errors that makes it fail validation by ``desktop-file-validate`. Probably replacing the word ``Description` by `Comment` would make it pass.

http://manpages.ubuntu.com/manpages/trusty/man1/desktop-file-validate.1.html

**Comment by panaaj** [comment]
I have uploaded a replacement NMEASimulator-1.0.1.AppImage file to the current v1.0.1 release that has `Description` removed from the desktop config.

**Comment by probonopd** [comment]
Thanks, this is solved now. :+1:
